In [ ]:
%load_ext rpy2.ipython


In [ ]:
%%R
## Introduction to Dataframes and operations in data frame
#Creating Data Frames
dataframe1 <- data.frame( name = c("Susanna","Mano","Juan"),
                        age = c(17,20,19))
print("Dataframe 1:")
print(dataframe1)

dataframe2 <- data.frame( Hobby = c("Quilling","Loom Bands","Chess"))
print("Dataframe 2:")
print(dataframe2)

dataframe3<-data.frame(name =c("Aldo","Anto"),age = c(23,21))
print("Dataframe 3:")
print(dataframe3)

#Accessing a coloumn in dataframe using [],[[]],$
res <- dataframe1[1]
print("Accessing Name coloumn in dataframe 1 :")
print(res)

res1 <- dataframe1[["name"]]
print("Accessing Name coloumn in dataframe 1 :")
print(res1)

res2 <- dataframe2$Hobby
print("Accessing Hobby coloumn in dataframe 2 :")
print(res2)

#Combining the dataframe using rbind() - combine vertically and cbind() - combine horizontally

rb <- rbind(dataframe1, dataframe3)
print("Doing Rbind() : ")
print(rb)

cb <- cbind(dataframe1,dataframe2)
print("Doing Cbind() : ")
print(cb)

#Finding the length of Dataframe
print("Length of Dataframe 1 : ")
len = length(dataframe1)
print(len)


[1] "Dataframe 1:"
     name age
1 Susanna  17
2    Mano  20
3    Juan  19
[1] "Dataframe 2:"
       Hobby
1   Quilling
2 Loom Bands
3      Chess
[1] "Accessing Name coloumn in dataframe 1 :"
     name
1 Susanna
2    Mano
3    Juan
[1] "Accessing Name coloumn in dataframe 1 :"
[1] "Susanna" "Mano"    "Juan"   
[1] "Accessing Hobby coloumn in dataframe 2 :"
[1] "Quilling"   "Loom Bands" "Chess"     
[1] "Dataframe 3:"
  name age
1 Aldo  23
2 Anto  21
[1] "Doing Rbind() : "
     name age
1 Susanna  17
2    Mano  20
3    Juan  19
4    Aldo  23
5    Anto  21
[1] "Doing Cbind() : "
     name age      Hobby
1 Susanna  17   Quilling
2    Mano  20 Loom Bands
3    Juan  19      Chess
[1] "Length of Dataframe 1 : "
[1] 2


In [ ]:
%%R
##Introduction to Arrays
#Creating an array of ndimensions
arr1<-array(c(1:12),dim =c(3,3,3))
print(arr1)

#Accessing an array element
el <- arr1[3,3,2]
print("Element accessed :")
print(el)

#From scratch
vec1 <- c(1,2,3)
vec2 <- c(4,5,6,7,8,9)

col_names <- c("col1","col2","col3")
row_names <- c("r1","r2","r3")
matrix_name <-c("matrix1","matrix2","matrix3")

res <- array(c(vec1,vec2),dim=c(3,3,3),dimnames = list(row_names,col_names,matrix_name))
print(res)

#Accessing a whole row or a whole coloumn
print("Accessing a whole row :")
row <- res[c(2),,3]
print(row)

print("Accessing a whole coloumn :")
col <-res[,c(2),3]
print(col)


, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10    1    4
[2,]   11    2    5
[3,]   12    3    6

, , 3

     [,1] [,2] [,3]
[1,]    7   10    1
[2,]    8   11    2
[3,]    9   12    3

[1] "Element accessed :"
[1] 6
, , matrix1

   col1 col2 col3
r1    1    4    7
r2    2    5    8
r3    3    6    9

, , matrix2

   col1 col2 col3
r1    1    4    7
r2    2    5    8
r3    3    6    9

, , matrix3

   col1 col2 col3
r1    1    4    7
r2    2    5    8
r3    3    6    9

[1] "Accessing a whole row :"
col1 col2 col3 
   2    5    8 
[1] "Accessing a whole coloumn :"
r1 r2 r3 
 4  5  6 


In [ ]:
%%R
##Introduction to Strings
 msg1<-"Hello Friends"
 msg2 <-"Hey Friends"
 msg3 <- "Goodmorning"
 msg4 <-"Hey Friends"

#To check length of string
len = nchar(msg1)
print("Lenght of msg1 :")
print(len)

#To combine any to strings using paste()
msg5<-paste(msg1,msg3)
print("Combining any 2 strings :")
print(msg5)

#To compare any two strings using ==
res <- msg1 == msg2
print(res)
res1<-msg2 == msg4
print(res1)

#Changing the string case
up<-toupper(msg1)
print("Upper case of msg1 :")
print(up)

low<-tolower(msg1)
print("Lower case of msg1 :")
print(low)

[1] "Lenght of msg1 :"
[1] 13
[1] "Combining any 2 strings :"
[1] "Hello Friends Goodmorning"
[1] FALSE
[1] TRUE
[1] "Upper case of msg1 :"
[1] "HELLO FRIENDS"
[1] "Lower case of msg1 :"
[1] "hello friends"


In [ ]:
%%R
## Control Structures in R
#Conditional Statement : IF,IF-ELSE,IF-ELSE-IF LADDER,SWITCH

#IF conditional

x <- 8
if(x%%2 == 0){
    print("Even")
}

#IF ELSE conditional
x <- 7
if(x%%2 == 0){
    print("Even")
}else{
    print("Odd")
}

#IF - ELSE - IF Ladder
quantity <- 80
if(quantity <20){
    print("Not good day!")
}else if(quantity >20 && quantity <= 30){
    print("Better day !")
}else{
    print("Amazingg Dayyyy !!")
}

#SWITCH case
x <- switch(2,"one","two","three")
print(x)

##Looping statements
#While loop
i=1
while(i<8){
    print(i)
    i = i+1
}
#For loop
for(x in 1:10){
    print(x)
}
fruits <-c("apple","banana","orange","kiwi","lemon")
for (fruit in fruits){
    print(fruit)
}
#Repeat Loop
x = 1
repeat{
    print(x)
    if(x == 7){
        break
    }
    x = x+1
}
##Jump Statement
#break - same example as that of repeat loop
x <- c(1:8)
for(i in x){
    if(i==7){
        next
    }
    print(i)
}

[1] "Even"
[1] "Odd"
[1] "Amazingg Dayyyy !!"
[1] "two"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] "apple"
[1] "banana"
[1] "orange"
[1] "kiwi"
[1] "lemon"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 8


In [ ]:
%%R
#R Functions
#function with arguments

factorial <- function(x){
    fact <- 1
    for (i in 1:x){
        fact = fact*i
    }
    cat("\nFactorial of given number : ",fact)

    }
factorial(5)

#function with default arguments
add = function(a = 7,b = 6){
    return(a+b)
}
res = add()
cat(" \nFunction call by default values :",add())
cat("\nFunction call by custom values :",add(8,2))
cat("\n")

##Looping Functions in R
m1<-matrix(c(1:25),nrow = 5,ncol = 5)
print(m1)
#Coloumn manipulation
a_m1 <- apply(m1,2,mean)
cat("Apply function in Coloumn :",a_m1)
cat("\n")
#Row Manipulation
a_m2 <- apply(m1,1,mean)
cat("Apply function in row :",a_m2)

#Lapply,Tapply,sapply

cat("\nPerforming Lapply :\n")
x <-c("Susan","Anto","Juan")
lapply(x,toupper)

cat("\nPerforming Sapply :\n")
x <-c("Susan","Anto","Juan")
sapply(x,toupper)

cat("\nPerforming Tapply :\n")
salary <- c(10000,20000,30000,70000,80000,35000)
jobs <-c("DS","AI","DS","SWE","SWE","AI")
tapply(salary,jobs,max)





Factorial of given number :  120 
Function call by default values : 13
Function call by custom values : 10
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
Apply function in Coloumn : 3 8 13 18 23
Apply function in row : 11 12 13 14 15
Performing Lapply :

Performing Sapply :

Performing Tapply :
   AI    DS   SWE 
35000 30000 80000 
